name=d9servo
version=1.0.0
author=d9ll
maintainer=d9ll
sentence=A simple and lightweight library for controlling 180 and 360 degree servos.
paragraph=d9servo provides an easy-to-use interface for Arduino hobbyists. It simplifies the process of controlling standard servos with angle methods and continuous rotation servos with speed methods, removing the need for manual mapping.
category=Device Control
url=https://github.com/d9ll/d9servo
architectures=*
depends=Servo
