name=d9servo
version=1.0.0
author=Gleb
maintainer=Gleb
sentence=Lightweight wrapper for Servo control with simple rot() and speed() interface.
paragraph=Simplifies control for both standard and 360-degree servos.
category=Device Control
url=
architectures=*
depends=Servo